package ai.ivira.app.features.imazh.ui

enum class ImazhProcessImageStyle(val value: String) {
    General("general"),
    Anime("anime"),
    FantasyArt("fantasy_art"),
    Cinematic("cinematic"),
    Photographic("Photographic"),
    ThreeD("3d"),
    DigitalArt("digital_art"),
    Comic("comic"),
    Poster("poster"),
    Isometric("isometric"),
    LowPoly("lowpoly"),
    AnalogFilm("analog_film"),
    PixelArt("pixel_art"),
    Origami("origami"),
    Texture("texture"),
    NeonPunk("neonpunk"),
    Abstract("abstract"),
    Constructivist("constructivist"),
    Cubist("cubist"),
    Graffiti("graffiti"),
    Impressionist("impressionist"),
    Pointillism("pointillism"),
    PopArt("pop_art"),
    Watercolor("watercolor"),
    Minecraft("minecraft"),
    Horror("horror"),
    Minimal("minimal"),
    Monochrome("monochrome"),
    Collage("collage"),
    Noir("noir"),
    Pencil("pencil")
}